### ISSUE TITLE
6주차 스터디 공지

### ISSUE THREAD

**Issue by Hongsomang** [taeiim/Android-Study#18]
6주차 발표자와 주제는 아래와 같습니다.

송시은 - kotlin
홍소망 - android jetpack

7/13 동아리 시간에 진행합니다.
확인해주시면 감사하겠습니다.

@taeiim @SongSieun @ParkSohyeon17

**Comment by ParkSohyeon17** [comment]
확인했습니다.
스터디 공지의 경우 발표 5일 전에 이슈가 등록되었으면 합니다.
