### ISSUE TITLE
8주차 스터디 공지

### ISSUE THREAD

**Issue by SongSieun** [taeiim/Android-Study#21]
8주차 발표자와 주제는 아래와 같습니다.

송시은 - Databinding
박소현 - ViewModel과 LiveData
박태임 - 리팩토링

7/30 ~ 8/4 사이에 스터디 시간에 진행합니다.
확인해주시면 감사하겠습니다.

@taeiim @SongSieun @ParkSohyeon17

**Comment by ParkSohyeon17** [comment]
확인했습니다.

**Comment by taeiim** [comment]
확인했습니다.
