### ISSUE TITLE
14회차 개인주제 제안

### ISSUE THREAD

**Issue by jinusong** [taeiim/Android-Study#35]
14회차에는 TCP-IP Socket과 Socket io에 대하여 발표하려고합니다.

위 문서를 읽어주시면 감사하겠습니다.
https://m.blog.naver.com/goldenkingll/70106915167
https://d2.naver.com/helloworld/1336
http://woowabros.github.io/woowabros/2017/09/12/realtime-service.html
https://github.com/socketio/socket.io-client-java

확인 부탁드립니다.
@SongSieun @SeungYongSon @PaperEd @taeiim

issue를 늦게 달아서 죄송합니다

**Comment by papered** [comment]
확인했습니다.
