### ISSUE TITLE
1주차 개인 주제 추가

### ISSUE THREAD

**Issue by ParkSohyeon17** [taeiim/Android-Study#4]
1주차에 발표하게 될 Android Architecture Pattern인 MVC,, MVP, MVVM의 예제 사이트를 추가해서 올립니다. 
https://academy.realm.io/kr/posts/eric-maxwell-mvc-mvp-and-mvvm-on-android/

발표 전까지 궁금한 점이 있으시면 말씀해주세요. 준비해서 가겠습니다.
확인 부탁드립니다.
@L91519 
@taeiim 
@Hongsomang

**Comment by taeiim** [comment]
질문은 언제까지 할 수 있나요 ?

**Comment by ParkSohyeon17** [comment]
질문은 발표 날짜로부터 이틀 전까지 올려주시면 미리 준비해서 가겠습니다.
이 외에 추가적인 질문은 발표 시간 때 말씀해주세요.

**Comment by L91519** [comment]
확인했습니다~

**Comment by Hongsomang** [comment]
확인 했습니다.~
