### ISSUE TITLE
2주차 개인 주제 제안

### ISSUE THREAD

**Issue by L91519** [taeiim/Android-Study#6]
2주차 발표 주제는 '새로 부상하는 Rx Java'입니다.
보다 원활한 스터디를 위해 다음 참고자료를 읽어주시길 바랍니다. 
+ https://academy.realm.io/kr/posts/mobilization-hugo-visser-rxjava-for-rest-of-us/
+ https://medium.com/@LIP/rxjava-29cfb3ceb4ca (1, 2, 3, 4)
+ https://www.slideshare.net/waynejo/gdg-41029986

이해가 가지 않는 부분은 2일 전까지 질문을 남겨주시길 바랍니다.
감사합니다.

@ParkSohyeon17 
@taeiim 
@Hongsomang 
확인 부탁드립니다.

**Comment by Hongsomang** [comment]
네 기대하겠습니다~~

**Comment by taeiim** [comment]
RxJava 기대되네요 ㅎㅎ 공부 열심히해서 가겠습니다

**Comment by ParkSohyeon17** [comment]
확인했습니다.

**Comment by SongSieun** [comment]
확인했습니다. 기대하겠습니다.
